[features]
seeds = false
skip-lint = false
[programs.localnet]
sklim = "6xNAdkbnPED3NqTLVmna7FpCgF6mWGG9JjT1FxADwWxp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/samnang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
